{% set name = "hyperscript" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyperscript-{{ version }}.tar.gz
  sha256: 77e9372c09dbf0ec0e18515cd7e13a44cac7cbf800362a1eac26d9f8c4abe2a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - hyperscript
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: HyperText with Python
  home: https://github.com/vchan/hyperscript
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
